# dev environment
services:
  app:
    build:
      context: ..
      dockerfile: .dev/Dockerfile
      target: dev
    working_dir: /app
    volumes:
      - ../:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"